# Generated by Django 5.2.4 on 2025-07-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_name_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
    ]
